### ISSUE TITLE
OMMBV was removed (pip install started failing)

### ISSUE THREAD

**Issue by sapols** [heliophysicsPy/pyhc-docker-environment#15]
OMMBV broke the pipeline because its pip install started failing. It's unclear exactly why, but it's failing while trying to [install extensions](https://github.com/CosmicStudioSoftware/OMMBV/blob/main/setup.py#L18-L19). 

It's probably on OMMBV to update their install code to fix the pip install? But based on how its setup.py is written, we could temporarily avoid including those extensions by doing `READTHEDOCS=True pip install OMMBV`. That shouldn't affect the pip-dep-tree output... But it sure feels like a bad hack...

```
Collecting OMMBV
  Using cached OMMBV-1.0.1.tar.gz (67 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      <string>:18: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
      Traceback (most recent call last):
        File "/Users/shpo9723/opt/anaconda3/envs/python_3_10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/shpo9723/opt/anaconda3/envs/python_3_10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/shpo9723/opt/anaconda3/envs/python_3_10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/private/var/folders/4f/t664wvxn4nd8864qfqwknh7r008q5h/T/pip-build-env-9wawv888/overlay/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 27, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by sapols** [comment]
Well that `READTHEDOCS=True` hack works, but then the job still fails later during `pip install -r requirements.txt` because OMMBV is in there. I don't want to rework the whole pipeline around hacking OMMBV in there so I've [temporarily removed it from the environment](https://github.com/heliophysicsPy/pyhc-docker-environment/blob/main/utils/generate_dependency_table.py#L75-L77) and opened an [issue](https://github.com/CosmicStudioSoftware/OMMBV/issues/62) in OMMBV's GitHub repo.

**Comment by sapols** [comment]
Note that I've also removed OMMBV from `import-test.ipynb` for the time being.

**Comment by sapols** [comment]
This is probably fixed now: https://github.com/CosmicStudioSoftware/OMMBV/issues/62#issuecomment-2784622627
